<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Teledok.Application.Shared\Teledok.Application.Shared.csproj" />
    <ProjectReference Include="..\Teledok.Contracts.Shared\Teledok.Contracts.Shared.csproj" />
    <ProjectReference Include="..\Teledok.Domain\Teledok.Domain.csproj" />
    <ProjectReference Include="..\Teledok.Infrastructure\Teledok.Infrastructure.csproj" />
  </ItemGroup>

</Project>
